language: node_js

notifications:
  email:
    on_success: never
    on_failure: change

env:
  - TYPESCRIPT=typescript@1.8
  - TYPESCRIPT=typescript@next

node_js:
  - "6"

install:
  - npm install
  - npm install -g ts-node typescript tslint

script:
  - npm test